---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: devops-toolkit-staging
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm
      sourceRef:
        kind: GitRepository
        name: devops-toolkit
  interval: 30s
  targetNamespace: staging
  values:
    image: nginx
      tag: latest
    ingress:
      host: staging.devops-toolkit..nip.io

